services:
  unirider-carpooling-platform:
    image: unirider-carpooling-platform:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod